### ISSUE TITLE
markdownlint not being enforced

### ISSUE THREAD

**Issue by NotNite** [PrismLauncher/prismlauncher.github.io#17]
This page uses markdownlint, but there are 26 errors listed with `markdownlint-cli2 "**/*.md"`. I don't have the energy to fix them right now, but this is too irritating for my linter obsessed brain to pass up.

Worth considering a GitHub action that automatically lints, like this one:

```yaml
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          files: .
```
